//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Article_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articles()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int ArticleId { get; set; }
        public int UserId { get; set; }
        public string Author { get; set; }
        public string Title { get; set; }
        public string ContentMarkdownText { get; set; }
        public string ContentText { get; set; }
        public System.DateTime PublishTime { get; set; }
        public string Category { get; set; }
        public int ReadCount { get; set; }
        public string FilePaths { get; set; }
        public string CoverPhotoUrl { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
